export { default as Home } from './Home.tsx'
export { default as About } from './About.tsx'
export { default as Contact } from './Contact.tsx'
export { default as Login } from './Login.tsx'
export { default as Register } from './Register.tsx'
