package com.backend.enums;

public enum NotificationType {
    BOOKING_CREATED,
    BOOKING_STATUS_CHANGED,
    BOOKING_CANCELLED,
    PAYMENT_SUCCEEDED,
    PAYMENT_FAILED,
    PAYMENT_REFUNDED,
    REVIEW_RECEIVED,
    PROPERTY_PENDING_VERIFICATION,
    PROPERTY_VERIFIED,
    PROPERTY_REJECTED,
    USER_PENDING_APPROVAL,
    USER_APPROVED,
    USER_REJECTED,
    ADMIN_PAYMENT_MONITORING,
    SYSTEM_ALERT
}

