import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

export interface PaymentInvoiceData {
  id: number
  invoiceId?: string
  description?: string
  amount: number
  status?: string
  type?: string
  date?: string
  property?: string
  location?: string
  bookingId?: number
  cardType?: string
  cardLast4?: string
  refundAmount?: number
  refundDate?: string
  refundReason?: string
}

const safe = (value?: string | number | null) => {
  if (value === null || value === undefined || value === '') return 'N/A'
  return String(value)
}

export const downloadPaymentInvoicePdf = (payment: PaymentInvoiceData) => {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })
  const pageWidth = doc.internal.pageSize.getWidth()
  const margin = 14

  const invoiceId = payment.invoiceId || `INV-${payment.id}`
  const generatedOn = new Date().toLocaleString('en-GB')

  doc.setFillColor(37, 99, 235)
  doc.roundedRect(margin, 12, 16, 16, 3, 3, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(10)
  doc.text('RW', margin + 8, 22, { align: 'center' })

  doc.setTextColor(17, 24, 39)
  doc.setFontSize(16)
  doc.text('RentWise Invoice', margin + 22, 18)
  doc.setFontSize(10)
  doc.setTextColor(75, 85, 99)
  doc.text('Payment receipt', margin + 22, 24)

  doc.setDrawColor(37, 99, 235)
  doc.setLineWidth(0.8)
  doc.line(margin, 32, pageWidth - margin, 32)

  autoTable(doc, {
    startY: 36,
    theme: 'grid',
    styles: { fontSize: 9, cellPadding: 3, textColor: [17, 24, 39] },
    headStyles: { fillColor: [243, 244, 246], textColor: [55, 65, 81], fontStyle: 'bold' },
    body: [
      ['INVOICE NO.', 'DATE', 'STATUS', 'BOOKING ID'],
      [
        invoiceId,
        safe(payment.date),
        safe(payment.status).toUpperCase(),
        payment.bookingId ? `#${payment.bookingId}` : 'N/A'
      ]
    ],
    columnStyles: {
      0: { cellWidth: 52 },
      1: { cellWidth: 45 },
      2: { cellWidth: 40 },
      3: { cellWidth: 45 }
    }
  })

  const detailsY = (doc as any).lastAutoTable.finalY + 8
  doc.setFontSize(12)
  doc.setTextColor(17, 24, 39)
  doc.text('Invoice Details', margin, detailsY)

  autoTable(doc, {
    startY: detailsY + 2,
    theme: 'striped',
    styles: { fontSize: 9, cellPadding: 3 },
    alternateRowStyles: { fillColor: [249, 250, 251] },
    body: [
      ['Description', safe(payment.description)],
      ['Property', safe(payment.property)],
      ['Location', safe(payment.location)],
      ['Type', safe(payment.type).replace('_', ' ').toUpperCase()],
      ['Amount', `$${Number(payment.amount || 0).toLocaleString()}`],
      ['Payment Method', `${safe(payment.cardType)} •••• ${safe(payment.cardLast4)}`],
      ['Refund Amount', payment.refundAmount ? `$${payment.refundAmount.toLocaleString()}` : 'N/A'],
      ['Refund Date', safe(payment.refundDate)],
      ['Refund Reason', safe(payment.refundReason)]
    ],
    columnStyles: {
      0: { cellWidth: 45, fontStyle: 'bold' },
      1: { cellWidth: 127 }
    }
  })

  const footerY = doc.internal.pageSize.getHeight() - 10
  doc.setFontSize(8)
  doc.setTextColor(107, 114, 128)
  doc.text('Generated by RentWise System', margin, footerY)
  doc.text(`Generated on ${generatedOn}`, pageWidth - margin, footerY, { align: 'right' })

  doc.save(`rentwise-invoice-${invoiceId}.pdf`)
}


