import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

export interface UserExportSummary {
  propertiesCount?: number
  bookingsCount?: number
  favoritesCount?: number
  reviewsCount?: number
  paymentsCount?: number
  paymentMethodsCount?: number
  notificationsCount?: number
}

export interface UserExportUser {
  id?: number | string
  firstName?: string
  lastName?: string
  email?: string
  phone?: string
  role?: string
  isActive?: boolean
  isVerified?: boolean
  joinedAt?: string
  lastLogin?: string
}

export interface UserDataExportPayload {
  user?: UserExportUser
  summary?: UserExportSummary
  exportedAt?: string
}

const formatDateTime = (value?: string) => {
  if (!value) {
    return 'N/A'
  }
  const date = new Date(value)
  if (Number.isNaN(date.getTime())) {
    return value
  }
  return new Intl.DateTimeFormat('en-GB', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  }).format(date)
}

const safeNumber = (value?: number) => (typeof value === 'number' ? value : 0)

export const downloadUserDataPdfReport = (payload: UserDataExportPayload) => {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })
  const pageWidth = doc.internal.pageSize.getWidth()
  const margin = 14
  const reportDate = formatDateTime(payload.exportedAt)
  const fullName = `${payload.user?.firstName ?? ''} ${payload.user?.lastName ?? ''}`.trim() || 'User'
  const reference = `RW-DATA-${Date.now().toString().slice(-6)}`

  // Header logo (system logo mark used in app)
  doc.setFillColor(37, 99, 235)
  doc.roundedRect(margin, 12, 16, 16, 3, 3, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(10)
  doc.text('RW', margin + 8, 22, { align: 'center' })

  // Header text
  doc.setTextColor(17, 24, 39)
  doc.setFontSize(16)
  doc.text('RentWise', margin + 22, 18)
  doc.setFontSize(10)
  doc.setTextColor(75, 85, 99)
  doc.text('User Data Report', margin + 22, 24)
  doc.setDrawColor(37, 99, 235)
  doc.setLineWidth(0.8)
  doc.line(margin, 32, pageWidth - margin, 32)

  // Meta table
  autoTable(doc, {
    startY: 36,
    theme: 'grid',
    styles: { fontSize: 9, cellPadding: 3, textColor: [17, 24, 39] },
    headStyles: { fillColor: [243, 244, 246], textColor: [55, 65, 81], fontStyle: 'bold' },
    body: [
      ['REPORT TYPE', 'GENERATED BY', 'DATE GENERATED', 'REFERENCE'],
      [
        'Full User Data Export',
        payload.user?.email ?? 'N/A',
        reportDate,
        reference
      ]
    ],
    columnStyles: {
      0: { cellWidth: 45 },
      1: { cellWidth: 55 },
      2: { cellWidth: 45 },
      3: { cellWidth: 35 }
    }
  })

  const summary = payload.summary ?? {}
  const summaryRows = [
    ['Properties', String(safeNumber(summary.propertiesCount))],
    ['Bookings', String(safeNumber(summary.bookingsCount))],
    ['Favorites', String(safeNumber(summary.favoritesCount))],
    ['Reviews', String(safeNumber(summary.reviewsCount))],
    ['Payments', String(safeNumber(summary.paymentsCount))],
    ['Payment Methods', String(safeNumber(summary.paymentMethodsCount))],
    ['Notifications', String(safeNumber(summary.notificationsCount))]
  ]

  const afterMetaY = (doc as any).lastAutoTable.finalY + 8

  // Profile section
  doc.setFontSize(12)
  doc.setTextColor(17, 24, 39)
  doc.text('Profile Information', margin, afterMetaY)

  autoTable(doc, {
    startY: afterMetaY + 2,
    theme: 'striped',
    styles: { fontSize: 9, cellPadding: 3 },
    alternateRowStyles: { fillColor: [249, 250, 251] },
    body: [
      ['Full Name', fullName],
      ['Email', payload.user?.email ?? 'N/A'],
      ['Phone', payload.user?.phone ?? 'N/A'],
      ['Role', payload.user?.role ?? 'N/A'],
      ['Status', payload.user?.isActive ? 'Active' : 'Inactive'],
      ['Verified', payload.user?.isVerified ? 'Yes' : 'No'],
      ['Joined At', formatDateTime(payload.user?.joinedAt)],
      ['Last Login', formatDateTime(payload.user?.lastLogin)]
    ],
    columnStyles: {
      0: { cellWidth: 42, fontStyle: 'bold' },
      1: { cellWidth: 130 }
    }
  })

  const afterProfileY = (doc as any).lastAutoTable.finalY + 8

  // Summary section
  doc.setFontSize(12)
  doc.text('Data Summary', margin, afterProfileY)

  autoTable(doc, {
    startY: afterProfileY + 2,
    head: [['Metric', 'Value']],
    body: summaryRows,
    theme: 'grid',
    styles: { fontSize: 10, cellPadding: 3 },
    headStyles: { fillColor: [37, 99, 235], textColor: [255, 255, 255] },
    columnStyles: {
      0: { cellWidth: 120 },
      1: { cellWidth: 52, halign: 'center', fontStyle: 'bold' }
    }
  })

  // Footer
  const footerY = doc.internal.pageSize.getHeight() - 10
  doc.setFontSize(8)
  doc.setTextColor(107, 114, 128)
  doc.text('Generated by RentWise System', margin, footerY)
  doc.text(`Generated on ${reportDate}`, pageWidth - margin, footerY, { align: 'right' })

  const filenameDate = new Date().toISOString().slice(0, 10)
  doc.save(`rentwise-user-data-report-${filenameDate}.pdf`)
}
