name: Fullstack CI/CD

on:
  push:
    branches: ["main"]

jobs:

  # 🔹 FRONTEND JOB
  frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install
      - run: npm run build
      - run: npm test --if-present

  # 🔹 BACKEND JOB
  backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v3

      # 👉 For Node backend
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install
      - run: npm test --if-present

      # 👉 OR if Spring Boot (Java)
      # - uses: actions/setup-java@v3
      #   with:
      #     java-version: '21'
      # - run: ./mvnw test